#!/usr/bin/env bash
source .env
terraform init
terraform apply -auto-approve \
  -var "app_version=$VERSION" \
  -var "client_id=$ARM_CLIENT_ID" \
  -var "client_secret=$ARM_CLIENT_SECRET" \
  -var "environment=$ENVIRONMENT" \
  -var "storage_account_name=$STORAGE_ACCOUNT_NAME" \
  -var "storage_access_key=$STORAGE_ACCESS_KEY"
